### ISSUE TITLE
Front End

### ISSUE THREAD

**Issue by knanahassouna1** [FACG5/News-Project#3]
Front End 
Relates #2 
- [ ] Create Server
- [ ] Create Route
- [ ] Create Function to API request
- [ ] Create Function For Handling  Home Page
- [ ] Create Function For Handling Error Page
- [ ] Create Function to Get Data (title , image , autor , url ) from JSON file
