### ISSUE TITLE
Front End

### ISSUE THREAD

**Issue by knanahassouna1** [FACG5/News-Project#4]
Front End 
Relates  #2 
- [ ]  Make Input Field With Button for submitting it in index.html 
- [ ]  Make Style of index.html.
- [ ] Make Error.html and Style it
- [ ] Make action listener  for submit button.
- [ ] Make xhr request to sent query to a server .
- [ ] make function to manipulate with response from xhr request.
